---
# tasks file for open_vm_tools

- name: Installing packages
  package:
     name: open-vm-tools
     state: present
     
- name: centos | starting and enabling open-vm-tools
  service: name=vmtoolsd.service state=restarted enabled=yes
  when: ansible_os_family == "RedHat"
